service:
  name: bff-invoke

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service}-${self:provider.stage}
  stage: ${opt:stage}
  region: ${env:AWS_REGION}

  tracing:
    lambda: true
    apiGateway: true 
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"

plugins:
  - serverless-offline

package:
  include:
    - src/

functions:
  health:
    handler: src/handler.handler
    timeout: 30
    events:
      - http:
          path: /health
          method: get