service:
  name: series

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service}-${self:provider.stage}
  stage: ${opt:stage}
  region: ${env:AWS_REGION}

  tracing:
    lambda: true
    apiGateway: true

  # TODO: These should only be the permissions to invoke the lambda functions
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"

plugins:
  - serverless-offline

package:
  include:
    - src/

functions:
  allSeries:
    handler: src/allSeries.handler
    timeout: 30

  episodesBySeriesId:
    handler: src/episodesBySeriesId.handler
    timeout: 30