service:
  name: primative-xray

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service}-${self:provider.stage}
  stage: ${opt:stage}
  region: ${env:AWS_REGION}

  tracing:
    lambda: true
    apiGateway: true 
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"

custom:
  dynamodbTableName: ${self:provider.stackName}-TestTable
  snsTopicName: ${self:provider.stackName}-TestTopic
  apiGatewayName: ${self:provider.stackName}-api


plugins:
  - serverless-offline

functions:
  health:
    handler: src/handler.handler
    timeout: 30
    environment:
      AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
      STACK_NAME: ${self:provider.stackName}
      DYNAMODB_TABLE_NAME: ${self:custom.dynamodbTableName}
      SNS_TOPIC_NAME: ${self:custom.snsTopicName}
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    events:
      - http:
          path: /health
          method: get

  health2:
    handler: src/handler.handler
    timeout: 30
    environment:
      AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
      STACK_NAME: ${self:provider.stackName}
      DYNAMODB_TABLE_NAME: ${self:custom.dynamodbTableName}
      SNS_TOPIC_NAME: ${self:custom.snsTopicName}
    events:
      - http:
          path: /health2
          method: get

  invokeMe:
    handler: src/invokeMe.handler
    timeout: 30
    environment:
      AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
      STACK_NAME: ${self:provider.stackName}
      DYNAMODB_TABLE_NAME: ${self:custom.dynamodbTableName}
      SNS_TOPIC_NAME: ${self:custom.snsTopicName}


package:
  include:
    - src/
    - node_modules/

resources:
  Resources:

    TestTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.dynamodbTableName}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH

    TestTopic:
      Type: AWS::SNS::Topic
      DeletionPolicy: Delete
      Properties:
        DisplayName: Topic Name
        TopicName: ${self:custom.snsTopicName}
